package lk.ijse.dilanCarSale.util;

public enum Routes {
    LOGIN,SIGN_UP,MANAGER,EMPLOYEE,DASHBOARD,SUPPLIER,VEHICLE,STOCK,PAYMENT,DASHBOARD_EMPLOYEE,VIEW_AVAILABILITY,CUSTOMER,PLACE_ORDER,
    STOCK_DETAILS, AFTER_LOGIN, SUPPLIER_PAYMENT
}
